/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliothequeRouteImport } from './routes/bibliotheque'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as ChoixpeauRouteImport } from './routes/choixpeau'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as CoupeRouteImport } from './routes/coupe'
import { Route as DuelsRouteImport } from './routes/duels'
import { Route as InventaireRouteImport } from './routes/inventaire'
import { Route as JeuxRouteImport } from './routes/jeux'
import { Route as QuetesRouteImport } from './routes/quetes'
import { Route as SorcierRouteImport } from './routes/sorcier'
import { Route as SuccesRouteImport } from './routes/succes'
import { Route as JeuxIndexRouteImport } from './routes/jeux.index'
import { Route as JeuxEchecsRouteImport } from './routes/jeux.echecs'
import { Route as JeuxMemoryRouteImport } from './routes/jeux.memory'
import { Route as JeuxPersonnageRouteImport } from './routes/jeux.personnage'
import { Route as JeuxPotionsRouteImport } from './routes/jeux.potions'
import { Route as JeuxQuidditchRouteImport } from './routes/jeux.quidditch'
import { Route as JeuxQuizRouteImport } from './routes/jeux.quiz'
import { Route as JeuxSortsRouteImport } from './routes/jeux.sorts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoixpeauRoute = ChoixpeauRouteImport.update({
  id: '/choixpeau',
  path: '/choixpeau',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupeRoute = CoupeRouteImport.update({
  id: '/coupe',
  path: '/coupe',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelsRoute = DuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => rootRouteImport,
} as any)
const InventaireRoute = InventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxRoute = JeuxRouteImport.update({
  id: '/jeux',
  path: '/jeux',
  getParentRoute: () => rootRouteImport,
} as any)
const QuetesRoute = QuetesRouteImport.update({
  id: '/quetes',
  path: '/quetes',
  getParentRoute: () => rootRouteImport,
} as any)
const SorcierRoute = SorcierRouteImport.update({
  id: '/sorcier',
  path: '/sorcier',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccesRoute = SuccesRouteImport.update({
  id: '/succes',
  path: '/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxIndexRoute = JeuxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxEchecsRoute = JeuxEchecsRouteImport.update({
  id: '/echecs',
  path: '/echecs',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxMemoryRoute = JeuxMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxPersonnageRoute = JeuxPersonnageRouteImport.update({
  id: '/personnage',
  path: '/personnage',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxPotionsRoute = JeuxPotionsRouteImport.update({
  id: '/potions',
  path: '/potions',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxQuidditchRoute = JeuxQuidditchRouteImport.update({
  id: '/quidditch',
  path: '/quidditch',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxQuizRoute = JeuxQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxSortsRoute = JeuxSortsRouteImport.update({
  id: '/sorts',
  path: '/sorts',
  getParentRoute: () => JeuxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/carte': typeof CarteRoute
  '/choixpeau': typeof ChoixpeauRoute
  '/classement': typeof ClassementRoute
  '/coupe': typeof CoupeRoute
  '/duels': typeof DuelsRoute
  '/inventaire': typeof InventaireRoute
  '/jeux': typeof JeuxRouteWithChildren
  '/quetes': typeof QuetesRoute
  '/sorcier': typeof SorcierRoute
  '/succes': typeof SuccesRoute
  '/jeux/echecs': typeof JeuxEchecsRoute
  '/jeux/memory': typeof JeuxMemoryRoute
  '/jeux/personnage': typeof JeuxPersonnageRoute
  '/jeux/potions': typeof JeuxPotionsRoute
  '/jeux/quidditch': typeof JeuxQuidditchRoute
  '/jeux/quiz': typeof JeuxQuizRoute
  '/jeux/sorts': typeof JeuxSortsRoute
  '/jeux/': typeof JeuxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/carte': typeof CarteRoute
  '/choixpeau': typeof ChoixpeauRoute
  '/classement': typeof ClassementRoute
  '/coupe': typeof CoupeRoute
  '/duels': typeof DuelsRoute
  '/inventaire': typeof InventaireRoute
  '/quetes': typeof QuetesRoute
  '/sorcier': typeof SorcierRoute
  '/succes': typeof SuccesRoute
  '/jeux/echecs': typeof JeuxEchecsRoute
  '/jeux/memory': typeof JeuxMemoryRoute
  '/jeux/personnage': typeof JeuxPersonnageRoute
  '/jeux/potions': typeof JeuxPotionsRoute
  '/jeux/quidditch': typeof JeuxQuidditchRoute
  '/jeux/quiz': typeof JeuxQuizRoute
  '/jeux/sorts': typeof JeuxSortsRoute
  '/jeux': typeof JeuxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/carte': typeof CarteRoute
  '/choixpeau': typeof ChoixpeauRoute
  '/classement': typeof ClassementRoute
  '/coupe': typeof CoupeRoute
  '/duels': typeof DuelsRoute
  '/inventaire': typeof InventaireRoute
  '/jeux': typeof JeuxRouteWithChildren
  '/quetes': typeof QuetesRoute
  '/sorcier': typeof SorcierRoute
  '/succes': typeof SuccesRoute
  '/jeux/echecs': typeof JeuxEchecsRoute
  '/jeux/memory': typeof JeuxMemoryRoute
  '/jeux/personnage': typeof JeuxPersonnageRoute
  '/jeux/potions': typeof JeuxPotionsRoute
  '/jeux/quidditch': typeof JeuxQuidditchRoute
  '/jeux/quiz': typeof JeuxQuizRoute
  '/jeux/sorts': typeof JeuxSortsRoute
  '/jeux/': typeof JeuxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bibliotheque'
    | '/carte'
    | '/choixpeau'
    | '/classement'
    | '/coupe'
    | '/duels'
    | '/inventaire'
    | '/jeux'
    | '/quetes'
    | '/sorcier'
    | '/succes'
    | '/jeux/echecs'
    | '/jeux/memory'
    | '/jeux/personnage'
    | '/jeux/potions'
    | '/jeux/quidditch'
    | '/jeux/quiz'
    | '/jeux/sorts'
    | '/jeux/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bibliotheque'
    | '/carte'
    | '/choixpeau'
    | '/classement'
    | '/coupe'
    | '/duels'
    | '/inventaire'
    | '/quetes'
    | '/sorcier'
    | '/succes'
    | '/jeux/echecs'
    | '/jeux/memory'
    | '/jeux/personnage'
    | '/jeux/potions'
    | '/jeux/quidditch'
    | '/jeux/quiz'
    | '/jeux/sorts'
    | '/jeux'
  id:
    | '__root__'
    | '/'
    | '/bibliotheque'
    | '/carte'
    | '/choixpeau'
    | '/classement'
    | '/coupe'
    | '/duels'
    | '/inventaire'
    | '/jeux'
    | '/quetes'
    | '/sorcier'
    | '/succes'
    | '/jeux/echecs'
    | '/jeux/memory'
    | '/jeux/personnage'
    | '/jeux/potions'
    | '/jeux/quidditch'
    | '/jeux/quiz'
    | '/jeux/sorts'
    | '/jeux/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliothequeRoute: typeof BibliothequeRoute
  CarteRoute: typeof CarteRoute
  ChoixpeauRoute: typeof ChoixpeauRoute
  ClassementRoute: typeof ClassementRoute
  CoupeRoute: typeof CoupeRoute
  DuelsRoute: typeof DuelsRoute
  InventaireRoute: typeof InventaireRoute
  JeuxRoute: typeof JeuxRouteWithChildren
  QuetesRoute: typeof QuetesRoute
  SorcierRoute: typeof SorcierRoute
  SuccesRoute: typeof SuccesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choixpeau': {
      id: '/choixpeau'
      path: '/choixpeau'
      fullPath: '/choixpeau'
      preLoaderRoute: typeof ChoixpeauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupe': {
      id: '/coupe'
      path: '/coupe'
      fullPath: '/coupe'
      preLoaderRoute: typeof CoupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duels': {
      id: '/duels'
      path: '/duels'
      fullPath: '/duels'
      preLoaderRoute: typeof DuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaire': {
      id: '/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof InventaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux': {
      id: '/jeux'
      path: '/jeux'
      fullPath: '/jeux'
      preLoaderRoute: typeof JeuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quetes': {
      id: '/quetes'
      path: '/quetes'
      fullPath: '/quetes'
      preLoaderRoute: typeof QuetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorcier': {
      id: '/sorcier'
      path: '/sorcier'
      fullPath: '/sorcier'
      preLoaderRoute: typeof SorcierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/succes': {
      id: '/succes'
      path: '/succes'
      fullPath: '/succes'
      preLoaderRoute: typeof SuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux/': {
      id: '/jeux/'
      path: '/'
      fullPath: '/jeux/'
      preLoaderRoute: typeof JeuxIndexRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/echecs': {
      id: '/jeux/echecs'
      path: '/echecs'
      fullPath: '/jeux/echecs'
      preLoaderRoute: typeof JeuxEchecsRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/memory': {
      id: '/jeux/memory'
      path: '/memory'
      fullPath: '/jeux/memory'
      preLoaderRoute: typeof JeuxMemoryRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/personnage': {
      id: '/jeux/personnage'
      path: '/personnage'
      fullPath: '/jeux/personnage'
      preLoaderRoute: typeof JeuxPersonnageRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/potions': {
      id: '/jeux/potions'
      path: '/potions'
      fullPath: '/jeux/potions'
      preLoaderRoute: typeof JeuxPotionsRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/quidditch': {
      id: '/jeux/quidditch'
      path: '/quidditch'
      fullPath: '/jeux/quidditch'
      preLoaderRoute: typeof JeuxQuidditchRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/quiz': {
      id: '/jeux/quiz'
      path: '/quiz'
      fullPath: '/jeux/quiz'
      preLoaderRoute: typeof JeuxQuizRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/sorts': {
      id: '/jeux/sorts'
      path: '/sorts'
      fullPath: '/jeux/sorts'
      preLoaderRoute: typeof JeuxSortsRouteImport
      parentRoute: typeof JeuxRoute
    }
  }
}

interface JeuxRouteChildren {
  JeuxEchecsRoute: typeof JeuxEchecsRoute
  JeuxMemoryRoute: typeof JeuxMemoryRoute
  JeuxPersonnageRoute: typeof JeuxPersonnageRoute
  JeuxPotionsRoute: typeof JeuxPotionsRoute
  JeuxQuidditchRoute: typeof JeuxQuidditchRoute
  JeuxQuizRoute: typeof JeuxQuizRoute
  JeuxSortsRoute: typeof JeuxSortsRoute
  JeuxIndexRoute: typeof JeuxIndexRoute
}

const JeuxRouteChildren: JeuxRouteChildren = {
  JeuxEchecsRoute: JeuxEchecsRoute,
  JeuxMemoryRoute: JeuxMemoryRoute,
  JeuxPersonnageRoute: JeuxPersonnageRoute,
  JeuxPotionsRoute: JeuxPotionsRoute,
  JeuxQuidditchRoute: JeuxQuidditchRoute,
  JeuxQuizRoute: JeuxQuizRoute,
  JeuxSortsRoute: JeuxSortsRoute,
  JeuxIndexRoute: JeuxIndexRoute,
}

const JeuxRouteWithChildren = JeuxRoute._addFileChildren(JeuxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliothequeRoute: BibliothequeRoute,
  CarteRoute: CarteRoute,
  ChoixpeauRoute: ChoixpeauRoute,
  ClassementRoute: ClassementRoute,
  CoupeRoute: CoupeRoute,
  DuelsRoute: DuelsRoute,
  InventaireRoute: InventaireRoute,
  JeuxRoute: JeuxRouteWithChildren,
  QuetesRoute: QuetesRoute,
  SorcierRoute: SorcierRoute,
  SuccesRoute: SuccesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
