/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChoixpeauRouteImport } from './routes/choixpeau'
import { Route as CoupeRouteImport } from './routes/coupe'
import { Route as InventaireRouteImport } from './routes/inventaire'
import { Route as JeuxRouteImport } from './routes/jeux'
import { Route as QuetesRouteImport } from './routes/quetes'
import { Route as SorcierRouteImport } from './routes/sorcier'
import { Route as SuccesRouteImport } from './routes/succes'
import { Route as JeuxIndexRouteImport } from './routes/jeux.index'
import { Route as JeuxEchecsRouteImport } from './routes/jeux.echecs'
import { Route as JeuxMemoryRouteImport } from './routes/jeux.memory'
import { Route as JeuxQuizRouteImport } from './routes/jeux.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoixpeauRoute = ChoixpeauRouteImport.update({
  id: '/choixpeau',
  path: '/choixpeau',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupeRoute = CoupeRouteImport.update({
  id: '/coupe',
  path: '/coupe',
  getParentRoute: () => rootRouteImport,
} as any)
const InventaireRoute = InventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxRoute = JeuxRouteImport.update({
  id: '/jeux',
  path: '/jeux',
  getParentRoute: () => rootRouteImport,
} as any)
const QuetesRoute = QuetesRouteImport.update({
  id: '/quetes',
  path: '/quetes',
  getParentRoute: () => rootRouteImport,
} as any)
const SorcierRoute = SorcierRouteImport.update({
  id: '/sorcier',
  path: '/sorcier',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccesRoute = SuccesRouteImport.update({
  id: '/succes',
  path: '/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxIndexRoute = JeuxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxEchecsRoute = JeuxEchecsRouteImport.update({
  id: '/echecs',
  path: '/echecs',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxMemoryRoute = JeuxMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => JeuxRoute,
} as any)
const JeuxQuizRoute = JeuxQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => JeuxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choixpeau': typeof ChoixpeauRoute
  '/coupe': typeof CoupeRoute
  '/inventaire': typeof InventaireRoute
  '/jeux': typeof JeuxRouteWithChildren
  '/quetes': typeof QuetesRoute
  '/sorcier': typeof SorcierRoute
  '/succes': typeof SuccesRoute
  '/jeux/echecs': typeof JeuxEchecsRoute
  '/jeux/memory': typeof JeuxMemoryRoute
  '/jeux/quiz': typeof JeuxQuizRoute
  '/jeux/': typeof JeuxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choixpeau': typeof ChoixpeauRoute
  '/coupe': typeof CoupeRoute
  '/inventaire': typeof InventaireRoute
  '/quetes': typeof QuetesRoute
  '/sorcier': typeof SorcierRoute
  '/succes': typeof SuccesRoute
  '/jeux/echecs': typeof JeuxEchecsRoute
  '/jeux/memory': typeof JeuxMemoryRoute
  '/jeux/quiz': typeof JeuxQuizRoute
  '/jeux': typeof JeuxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choixpeau': typeof ChoixpeauRoute
  '/coupe': typeof CoupeRoute
  '/inventaire': typeof InventaireRoute
  '/jeux': typeof JeuxRouteWithChildren
  '/quetes': typeof QuetesRoute
  '/sorcier': typeof SorcierRoute
  '/succes': typeof SuccesRoute
  '/jeux/echecs': typeof JeuxEchecsRoute
  '/jeux/memory': typeof JeuxMemoryRoute
  '/jeux/quiz': typeof JeuxQuizRoute
  '/jeux/': typeof JeuxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choixpeau'
    | '/coupe'
    | '/inventaire'
    | '/jeux'
    | '/quetes'
    | '/sorcier'
    | '/succes'
    | '/jeux/echecs'
    | '/jeux/memory'
    | '/jeux/quiz'
    | '/jeux/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choixpeau'
    | '/coupe'
    | '/inventaire'
    | '/quetes'
    | '/sorcier'
    | '/succes'
    | '/jeux/echecs'
    | '/jeux/memory'
    | '/jeux/quiz'
    | '/jeux'
  id:
    | '__root__'
    | '/'
    | '/choixpeau'
    | '/coupe'
    | '/inventaire'
    | '/jeux'
    | '/quetes'
    | '/sorcier'
    | '/succes'
    | '/jeux/echecs'
    | '/jeux/memory'
    | '/jeux/quiz'
    | '/jeux/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChoixpeauRoute: typeof ChoixpeauRoute
  CoupeRoute: typeof CoupeRoute
  InventaireRoute: typeof InventaireRoute
  JeuxRoute: typeof JeuxRouteWithChildren
  QuetesRoute: typeof QuetesRoute
  SorcierRoute: typeof SorcierRoute
  SuccesRoute: typeof SuccesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choixpeau': {
      id: '/choixpeau'
      path: '/choixpeau'
      fullPath: '/choixpeau'
      preLoaderRoute: typeof ChoixpeauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupe': {
      id: '/coupe'
      path: '/coupe'
      fullPath: '/coupe'
      preLoaderRoute: typeof CoupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaire': {
      id: '/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof InventaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux': {
      id: '/jeux'
      path: '/jeux'
      fullPath: '/jeux'
      preLoaderRoute: typeof JeuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quetes': {
      id: '/quetes'
      path: '/quetes'
      fullPath: '/quetes'
      preLoaderRoute: typeof QuetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorcier': {
      id: '/sorcier'
      path: '/sorcier'
      fullPath: '/sorcier'
      preLoaderRoute: typeof SorcierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/succes': {
      id: '/succes'
      path: '/succes'
      fullPath: '/succes'
      preLoaderRoute: typeof SuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux/': {
      id: '/jeux/'
      path: '/'
      fullPath: '/jeux/'
      preLoaderRoute: typeof JeuxIndexRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/echecs': {
      id: '/jeux/echecs'
      path: '/echecs'
      fullPath: '/jeux/echecs'
      preLoaderRoute: typeof JeuxEchecsRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/memory': {
      id: '/jeux/memory'
      path: '/memory'
      fullPath: '/jeux/memory'
      preLoaderRoute: typeof JeuxMemoryRouteImport
      parentRoute: typeof JeuxRoute
    }
    '/jeux/quiz': {
      id: '/jeux/quiz'
      path: '/quiz'
      fullPath: '/jeux/quiz'
      preLoaderRoute: typeof JeuxQuizRouteImport
      parentRoute: typeof JeuxRoute
    }
  }
}

interface JeuxRouteChildren {
  JeuxEchecsRoute: typeof JeuxEchecsRoute
  JeuxMemoryRoute: typeof JeuxMemoryRoute
  JeuxQuizRoute: typeof JeuxQuizRoute
  JeuxIndexRoute: typeof JeuxIndexRoute
}

const JeuxRouteChildren: JeuxRouteChildren = {
  JeuxEchecsRoute: JeuxEchecsRoute,
  JeuxMemoryRoute: JeuxMemoryRoute,
  JeuxQuizRoute: JeuxQuizRoute,
  JeuxIndexRoute: JeuxIndexRoute,
}

const JeuxRouteWithChildren = JeuxRoute._addFileChildren(JeuxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChoixpeauRoute: ChoixpeauRoute,
  CoupeRoute: CoupeRoute,
  InventaireRoute: InventaireRoute,
  JeuxRoute: JeuxRouteWithChildren,
  QuetesRoute: QuetesRoute,
  SorcierRoute: SorcierRoute,
  SuccesRoute: SuccesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
